### PR TITLE
Check peerid test

### LINKED ISSUE #7: rustls::ServerCertVerifier should check remote_public_key
https://github.com/ipfs-rust/libp2p-quic/blob/f2a860282288138128a6aecc14eb9b96df924a9a/src/crypto.rs#L117

According to https://github.com/libp2p/specs/blob/master/tls/tls.md#libp2p-public-key-extension, the given `remote_public_key` should be checked inside `ServerCertVerifier::verify_server_cert` against `Libp2pExtension::peer_key`:

> The public host key allows the peer to calculate the peer ID of the peer it is connecting to. Clients MUST verify that the peer ID derived from the certificate matches the peer ID they intended to connect to, and MUST abort the connection if there is a mismatch.

### PR DESCRIPTION
**Pull request by dvc94ch**
Think I was right after all. @kpp do the new tests satisfy your concerns about #7?

Closes #7

### CODE REVIEW

**Comment by kpp** [comment]
> do the new tests satisfy your concerns

No, because there could be a real node with a "`fake_peer_id`" controlled by **Mallory**. So far your tests pass because it is unlikely that either a or b got an address equal to fake_peer_id.

**Comment by dvc94ch** [comment]
Can you elaborate? Maybe add a test you think should fail but doesn't?

**Comment by kpp** [comment]
Yes, you should create swarms **a**, **b**, **c**, construct a cert signed with **c** and give it to **b**. When dialing from **a** to **b**, **b** should provide a **c**'s cert.

**Comment by dvc94ch** [comment]
Isn't that problem with self-signed certificates in general? in noise terminology what you'd do to authenticate a NN handshake with signatures is you'd sign the ephemeral public key. however self signed certificates don't contain any randomness from what I understand so they can be shown to anybody.

**Comment by kpp** [comment]
Yes, but the whole idea of the libp2p extension is to prove with the signature that you own a secret key of the client you are dialing to.

**Pull request merged**
